'use strict';
const problem29 = require('./problem-0029');

console.time('Elapsed Time');

let input = 100;
let result = problem29.distinctPowers(input);

console.log(`How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ ${input} and 2 ≤ b ≤ ${input}?`);
console.log(`${result}`);
console.timeEnd('Elapsed Time');