'use strict';
const BigNumber = require('bignumber.js');
BigNumber.config({ EXPONENTIAL_AT: 1e+9 });
BigNumber.config({ POW_PRECISION: 1e+9 });

/**
 * Finds the number of distinct terms in the sequence generated by a^b for 2 ≤ a ≤ max and 2 ≤ b ≤ max
 * @param {Number} max
 * @returns {Number}
 */
exports.distinctPowers = (max) => {
  let powers = new Set();
  for (let a = 2; a <= max; a++) {
    for (let b = 2; b <= max; b++) {
      let power = new BigNumber(a).pow(b).toNumber();
      powers.add(power);
    }
  }
  return powers.size;
};
